### ISSUE TITLE
Identify transistors

### ISSUE THREAD

**Issue by vinicentus** [vvigilante/comelit-simplebus1#3]
Hello!

Would it be possible to document the model numbers of the transistors used in the different parts of the cricuit? As of now they are missing.

I'm trying to build something similar but it's hard to figure out what the different transistors are used for and what specs they need to have.

Br.
Vincent

**Comment by vvigilante** [comment]
I used bc327/8 all over.

**Comment by vinicentus** [comment]
Thank you! That helps a lot!

**Comment by vinicentus** [comment]
Do you want this issue closed or should I leave it open? Btw, [this](https://github.com/vvigilante/comelit-simplebus1/blob/main/sketch_webmonitor/README.md) was very helpful as well for understanding the circuit.

**Comment by vinicentus** [comment]
May I still ask what current gain was used? Here are a couple of different versions of the BC327 (more info [here](https://www.el-component.com/bipolar-transistors/bc327) under the Hfe seciton)

**Comment by vvigilante** [comment]
BC337-25 maybe? Found that in my purchase history.
I don't have the exact data handy unfortunately. I just grabbed whatever transistors I had laying around at the time. I'm not an EE, but I think it's not going to matter a whole lot. There was not though put into the choice of transistor, basically.

**Comment by vinicentus** [comment]
Okay.
Thank you for the answer!
I'll try to build this unit and see how it goes.

**Comment by vinicentus** [comment]
Did you by any chance mean BC337? Because they are NPN transistors, as in the schematic. BC327 are PNP transistors, which aren't used at all (it seems).

**Comment by vvigilante** [comment]
Yes BC337-25

**Comment by vinicentus** [comment]
Yeah, okay, thanks :D
